### ISSUE TITLE
Question: is it safe to use with multiple service replicas?

### ISSUE THREAD

**Issue by skhoroshavin** [BurntSushi/migration#1]
Let's say we have 10 replicas of stateless service talking to database that we need to update (and that update includes new migration), and we start updating them by batches of 2 for example. Do I understand it correctly that this should still work, because schema update is transactional, so only the transaction that committed first would be actually committed, and second would fail without any ill effects except that db "wrapped connection" itself would fail and need to be recreated? Or there are some other gotchas with that approach?

Also, did you consider adding:
* either retry logic in case of failed commit
* or using explicit database lock

and if not, then why?

So I guess answer to question in title is "yes", but I'd like to have a better confidence that my understanding is correct )

**Comment by BurntSushi** [comment]
The last commit for this project is a little over 7.5 years ago. And that's probably the last time I looked at the code. You're on your own, sorry.

> schema update is transactional

That depends on which database system you're using I guess.

**Comment by skhoroshavin** [comment]
@BurntSushi so, you're not using it (or similar approach in other languages) now, right?

> That depends on which database system you're using I guess.

Main cases are MySQL or Postgres, I will look into corresponding docs, was just hoping you have a quick answer

**Comment by BurntSushi** [comment]
I'm not an authority on database systems. You'll need to do your own research.

> so, you're not using it (or similar approach in other languages) now, right?

I am not using this package, no.

**Comment by skhoroshavin** [comment]
Okay, thanks :)
